//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace M2E4Win.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("M2E4Win.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   // に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ComSp {
            get {
                return ResourceManager.GetString("ComSp", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config1 {
            get {
                return ResourceManager.GetString("Config1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config2 {
            get {
                return ResourceManager.GetString("Config2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config3 {
            get {
                return ResourceManager.GetString("Config3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;configuration&gt;
        ///  &lt;configSections&gt;
        ///    &lt;!-- For more information on Entity Framework configuration, visit http://go.microsoft.com/fwlink/?LinkID=237468 --&gt;
        ///    &lt;section name=&quot;entityFramework&quot; type=&quot;System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot; requirePermission=&quot;false&quot;/&gt;
        ///  &lt;/configSections&gt;
        ///  &lt;startup&gt;
        ///    &lt;supportedRuntime version=&quot;v4.0&quot; sku=&quot;.NETFramework,Version=v4.5 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string configxml1 {
            get {
                return ResourceManager.GetString("configxml1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        ///    providerName=&quot;MySql.Data.MySqlClient&quot; /&gt;
        ///  &lt;/connectionStrings&gt;
        ///&lt;/configuration&gt;
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string configxml2 {
            get {
                return ResourceManager.GetString("configxml2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   \ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirSp {
            get {
                return ResourceManager.GetString("DirSp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   } に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EB {
            get {
                return ResourceManager.GetString("EB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   //------------------------------------------------------------------------------------------------ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Header1 {
            get {
                return ResourceManager.GetString("Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   //    このコードはMySqlToEntityで生成されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Header2 {
            get {
                return ResourceManager.GetString("Header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   //    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Header3 {
            get {
                return ResourceManager.GetString("Header3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   //    このファイルに対する手動の変更は、コードが再生成されると上書きされます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Header4 {
            get {
                return ResourceManager.GetString("Header4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   { に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SB {
            get {
                return ResourceManager.GetString("SB", resourceCulture);
            }
        }
    }
}
